name: Generate Analytic Events

on:
  push:
    branches: [ main ]
    paths:
      - 'Events.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:

    - name: Get swift version # GH Linux images contain the latest stable Swift version
      run: swift --version # Swift 5.10.0

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Command
      run: swift run AnalyticsGenerator --input Events.md

    # Commit all changed files back to the repository
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate analytic events
